services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
        reservations:
          cpus: "0.1"
          memory: "25MB"

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api1
    environment:
      - PORT=9999
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
        reservations:
          cpus: "0.3"
          memory: "75MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha-api2
    environment:
      - PORT=9999
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
        reservations:
          cpus: "0.3"
          memory: "75MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
